---
title: "group_document"
format: html
editor: source
---

# Puck

Hello!!!

```{r}
5+5 # I can't do math
```

## New stuff

Here is some more math

```{r}
2+7
3+9
10/3
```


# Zi

```{r}
2+2
1:100
3*3
sample(1:9)
X <- matrix(sample(1:9), nrow = 3, ncol = 3)
X
sum(X)
mean(X)
?sum
sum
nucleotides <- c("a", "c", "g", "t")
nucleotides
sample(nucleotides, size = 100, replace = TRUE)
table(sample(nucleotides, size = 100, replace = TRUE))
paste0(sample(nucleotides, size = 100, replace = TRUE), collapse = "")
replicate(n = 10, expr = paste0(sample(nucleotides, size = 100, replace = TRUE), collapse = ""))
df <- data.frame(id = paste0("seq", 1:10), seq = replicate(n = 10, expr = paste0(sample(nucleotides, size = 100, replace = TRUE), collapse = "")))
df
str(df)
ls()
```


# Dani

```{r}
library("tidyverse")

xy <- seq(from = -3,
          to = 3, 
          by = 0.01)
expand_grid(x = xy,
            y = xy) |>
  ggplot(
    mapping = aes(
      x = (1 + x - sin(y^2)),
      y = (1 - y - cos(x^2)))) +
  geom_point(alpha = 0.05,
             shape = 20,
             size = 0) + 
  theme_void() +
  coord_polar()
```

